
  db.coches.find({"marca": "mercedes"}).pretty()
 db.coches.find({"año": 2020}).pretty()
      db.coches.find({"caballos": 140}).pretty()
      db.coches.find({"marca": "renault"}).pretty()
 db.coches.find({"año": 2000}).pretty()
      db.coches.find({"caballos": 100}).pretty()
      db.coches.find({"marca": "BMW"}).pretty()
 db.coches.find({"año": 2003}).pretty()
      db.coches.find({"caballos": 70}).pretty()
      db.coches.find({"marca": "Fiat"}).pretty()
 db.coches.find({"año": 1990}).pretty()
      db.coches.find({"caballos": 90}).pretty()
      db.coches.find({"marca": "Ford"}).pretty()
 db.coches.find({"año": 2010}).pretty()
      db.coches.find({"caballos": 120}).pretty()
      db.coches.find({"marca": "mercedes"}).pretty()
 db.coches.find({"año": 2001}).pretty()
      db.coches.find({"caballos": 40}).pretty()
      db.coches.find({"marca": "mercedes"}).pretty()
 db.coches.find({"año": 1995}).pretty()
      db.coches.find({"caballos": 45}).pretty()
      db.coches.find({"caballos": { $eq: 120 } }).pretty()
      db.coches.find({"caballos": { $lt: 100 } }).pretty()
      db.coches.find({"caballos": { $gt: 60 } }).pretty()
      db.coches.find({"caballos": { $eq: 140 } }).pretty()
      db.coches.find({"caballos": { $lte: 120 } }).pretty()
      db.coches.find({"caballos": { $gte: 100 } }).pretty()
      db.coches.find({"caballos": { $nin: 140 } }).pretty()
      db.coches.find({"caballos": { $ne: 40 } }).pretty()

